[book]
authors = ["Stanislav B."]
title = "GFM Frame"
language = "ru"
multilingual = false
src = "src"

[output.html]
google-analytics = "G-92XE0TFE7Y"

[output.html.print]
enable = false

[output.html.search]
enable = false