[book]
authors = ["Stanislav B."]
title = "GFM Frame"
language = "ru"
multilingual = false
src = "src"

[output.html.print]
enable = false

[output.html.search]
enable = true

[output.html]
additional-js = [
    "theme/js/elasticlunr.js",
    "theme/js/lunr.stemmer.support.js",
    "theme/js/lunr.ru.js",
    "theme/js/mark.min.js",
    "theme/js/searcher.js"
]